#!/bin/bash

filename="restart"
extension="bin"

watch_dir=$(pwd)
counter=0

inotifywait -m -e close_write --format "%f" "$watch_dir" | while read newfile

do
    if [[ "${newfile}" == "${filename}.${extension}" ]]; then

        new_name="${filename}_${counter}.${extension}"

        cp "${watch_dir}/${filename}.${extension}" "${watch_dir}/${new_name}"

        echo "Renamed ${filename}.${extension} to ${new_name}"

        ((counter++))

    fi
done
