#!/bin/bash

cd run
initialize_field <<EOF
cfl3d.inp
restart.bin
1
0
0
1
1,0,0,0,0.714285714
EOF

mkdir ../data

mpirun -np 4 cfl3d_mpi < cfl3d.inp

mv cfl3d.prout ../data/cfl3d.prout
mv cfl3d.out ../data/cfl3d.out
mv cfl3d.res ../data/cfl3d.res
mv cfl3d.subit_res ../data/cfl3d.subit_res

mv 45deg.py ../data/45deg.py
mv chamber.png ../data/chamber.png
mv exit.png ../data/exit.png
mv no10.png ../data/no10.png
mv no6co.png ../data/no6co.png
mv no6mi.png ../data/no6mi.png
mv no6fi.png ../data/no6fi.png
cp cfl3d.inp ../data/cfl3d.inp

cd ../data

python ./45deg.py
