#!/usr/bin/env python3
from scipy.io import FortranFile
import numpy as np
import re
import shutil
import math
import os
import sys
import yaml

def READ_YAML():
     global config,config_file
     config_file = sys.argv[1]
     with open(config_file, "r") as f:
         config = yaml.safe_load(f)

     shutil.rmtree("0",ignore_errors=True)
     shutil.rmtree("run",ignore_errors=True)
     shutil.rmtree("con",ignore_errors=True)
     shutil.rmtree("data",ignore_errors=True)
     shutil.copytree(config["Auxiliary"]["base_folder"], "0")

def SPLITTER():
     if config["Splitter"][0]["split_fn"] is not None:

     # remove XXX in input file
         os.chdir("0")
         with open(config["Auxiliary"]["input_fn"], "r") as file:
             content = file.read()

         content = content.replace("XXX", "0")

         with open(config["Auxiliary"]["input_fn"], "w") as file:
             file.write(content)

     # read grid sizes 
         grid = FortranFile(config["InputOutputFiles"][0],"r")
         nblk = grid.read_ints(np.int32).item(0)
         bdims = grid.read_ints(np.int32).reshape((nblk,3))
         grid.close()
        
     # split calculations
         block_cell = np.int32([math.prod(sublist) for sublist in bdims-1])
         ncell = sum(block_cell)
         if config["Auxiliary"]["platform"] == "hpc":
             cell_core = ncell/(config["Auxiliary"]["ncore"]-1)

             nested_list = []
             for n in range(nblk):
             # split only k direction
                 ncell = math.prod(bdims[n]-1)
                 nsplit = ncell/cell_core
                 ks = int((bdims[n][2]-1)/nsplit)
 
                 while ks*(bdims[n][1]-1) < cell_core :
                     ks += 1

                 list = []
                 i=0
                 ksi = 0
                 while ksi < bdims[n][2]-ks:
                     if i == 0 :
                         ksi += ks +1
                     else :
                         ksi += ks
                     i+= 1
                     if (bdims[n][2] - ksi) > 2:
                         list.append(ksi)

                 nested_list.append(list)

         elif config["Auxiliary"]["platform"] == "mypc":
             cell_core = ncell/(config["Auxiliary"]["ncore_mypc"]-1)

             sorted_indices = np.argsort(block_cell)
             sorted_arr = block_cell[sorted_indices]

             splitted = [] ; indicesl = []
             current_sum = 0 ; current_group = 0
             for idx, val in zip(sorted_indices, sorted_arr):
                 if current_sum + val < cell_core or np.isclose(current_sum + val, cell_core, atol=1):
                     current_sum += val
                 else:
                     overflow = (current_sum + val) - cell_core
                     splitted.append(overflow)
                     indicesl.append(idx)
                     current_group += 1
                     current_sum = overflow
             
             ksi = []
             for i in range(len(indicesl)):
                 ksi.append(round(splitted[i]/(bdims[i][1]-1)))

             nested_list = [None] * nblk
             for idx,ksind in zip(indicesl,ksi):
                 nested_list[idx] = [ksind]

         nsplit = sum(len(sublist) if sublist is not None else 0 for sublist in nested_list)

         transformed_list = [[[i+1, 3, element] for element in sublist] if sublist is not None else [] for i, sublist in enumerate(nested_list) ]
     # create split file
         with open(config["Splitter"][0]["split_fn"], "w") as f:
             f.write("INPUT (UNSPLIT) FILES\n")
             f.write(config["Auxiliary"]["input_fn"]+"\n")
             f.write((config["Splitter"][0]["ronnie_fn"] if config["Splitter"][0]["ronnie_fn"] is not None else "null") + "\n")
             f.write(config["InputOutputFiles"][0]+"\n")
             f.write((config["Splitter"][0]["sdgrid_fn"] if config["Splitter"][0]["sdgrid_fn"] is not None else "null") + "\n")
             f.write("ICFLVER   IRONVER   IGRDFMT    ISDFMT\n")
             f.write(f"{config['Splitter'][1]['ICFLVER']:7}"
                     f"{config['Splitter'][1]['IRONVER']:10}"
                     f"{config['Splitter'][1]['IGRDFMT']:10}"
                     f"{config['Splitter'][1]['ISDFMT']:10}\n")
             f.write("OUTPUT (SPLIT) FILES\n")
             f.write(config["Auxiliary"]["input_fn"]+ "_split\n")
             f.write((config["Splitter"][0]["ronnie_fn"] + "_split\n" ) if config["Splitter"][0]["ronnie_fn"] is not None else "null\n")
             f.write(config["InputOutputFiles"][0]+"_split\n")
             f.write((config["Splitter"][0]["sdgrid_fn"] + "_split\n" ) if config["Splitter"][0]["sdgrid_fn"] is not None else "null\n")
             f.write("ICFLVER   IRONVER   IGRDFMT    ISDFMT\n")
             f.write(f"{config['Splitter'][2]['ICFLVER']:7}"
                     f"{config['Splitter'][2]['IRONVER']:10}"
                     f"{config['Splitter'][2]['IGRDFMT']:10}"
                     f"{config['Splitter'][2]['ISDFMT']:10}\n")
             f.write("NSPLITS\n")
             f.write(f"{nsplit}\n")
             for sublist in transformed_list:
                 for triplet in sublist:
                     for item in triplet:
                         f.write(f"{item}\n") 
    
         os.system(f"splitter < {config["Splitter"][0]["split_fn"]}")
         os.remove("splitter.error")
         os.remove(config["InputOutputFiles"][0])
         os.remove(config["Auxiliary"]["input_fn"])
         os.remove(config["Splitter"][0]["split_fn"])
         os.chdir("../")

def READ_PLOT3D_GRID(fn):
     grid = FortranFile(fn,"r")
     nblk = grid.read_ints(np.int32).item(0)
     bdims = grid.read_ints(np.int32).reshape((nblk,3))
     maxdims = np.max(bdims, axis=0)

     x = np.zeros((*maxdims,nblk))
     y = np.zeros((*maxdims,nblk))
     z = np.zeros((*maxdims,nblk))

     for n in range(nblk):
         tempblk = grid.read_reals(np.float64)
         x[:bdims[n,0],:bdims[n,1],:bdims[n,2],n] = tempblk[:int(tempblk.size/3)].reshape(*bdims[n],order="F")
         y[:bdims[n,0],:bdims[n,1],:bdims[n,2],n] = tempblk[int(tempblk.size/3):2*int(tempblk.size/3)].reshape(*bdims[n],order="F")
         z[:bdims[n,0],:bdims[n,1],:bdims[n,2],n] = tempblk[2*int(tempblk.size/3):].reshape(*bdims[n],order="F")

     grid.close()
     return nblk,bdims,x,y,z

def FIND_INDEXES(fn):
     nblk,bdims,x,y,z = READ_PLOT3D_GRID(fn)
     blocks_list = []
     indices_list = []
     for probe in config["PrintOutputSpecifications"][:config["OptionsAndSpecifications"]["NPRINT"]]:
         min_dist = np.inf
         closest_indices = None
         closest_block = -1
         for n in range(nblk):
             # Calculate the squared distance for all points in the block
             dist_sq = (x[:bdims[n,0],:bdims[n,1],:bdims[n,2],n] - probe["X"])**2 + \
                       (y[:bdims[n,0],:bdims[n,1],:bdims[n,2],n] - probe["Y"])**2 + \
                       (z[:bdims[n,0],:bdims[n,1],:bdims[n,2],n] - probe["Z"])**2

             # Find the minimum distance and its index in the current block
             min_dist_block = np.min(dist_sq)
             if min_dist_block < min_dist:
                 min_dist = min_dist_block
                 # Find the index of the minimum distance
                 idx = np.unravel_index(np.argmin(dist_sq), dist_sq.shape)
                 closest_indices = (idx[0] + 1, idx[1] + 1, idx[2] + 1)
                 closest_block = n + 1

         blocks_list.append(closest_block)
         indices_list.append(closest_indices)    
     return blocks_list, indices_list

def CFL3Dinp():
     os.chdir("0")
     if config["Splitter"][0]["split_fn"] is not None: 
         config["Auxiliary"]["input_fn"] = config["Auxiliary"]["input_fn"] + "_split"
         config["InputOutputFiles"][0] = config["InputOutputFiles"][0] + "_split"

     with open(config["Auxiliary"]["input_fn"]) as f:
         for line in f:
             if "ngrid" in line.lower():
                 config["OptionsAndSpecifications"]["NGRID"] = next(f).split()[line.split().index("ngrid")]
                 if config["OptionsAndSpecifications"]["NPLOT3D"]:
                     config["OptionsAndSpecifications"]["NPLOT3D"] = abs(int(config["OptionsAndSpecifications"]["NGRID"]))
                 else:
                     config["OptionsAndSpecifications"]["NPLOT3D"] = 0
                 break  
             
         for line in f:
             if "idim" in line.lower():
                 blocks_splitted = [next(f) for _ in range(abs(int(config["OptionsAndSpecifications"]["NGRID"])))]
                 break

         copy = False; bc_all = []
         for line in f:
             if " grid " in line: copy = True
             if "mseq" in line: break
             if copy: bc_all.append(line)
         
         copy = False; one2one_blocking = []
         for line in f:
             if "1-1" in line: copy = True
             if "patch" in line: break
             if copy: one2one_blocking.append(line)

     for i, line in enumerate(bc_all):
         if 2002 in config["BoundaryConditions"]:
             if "p/pinf" in line.lower():
                 bc_all[i + 1] = " "*6 + str(config["BoundaryConditions"][2002]["P_Pinf"]) + "\n"

         if 2009 in config["BoundaryConditions"]:
             if line.strip() == "      mach   pt/pinf   tt/tinf     alpha      beta".strip():
                 parts = re.findall(r'\s*\S+', bc_all[i-1])
                 parts[2] = parts[2].replace("2003", "2009")
                 parts[7] = parts[7].replace("5", "8")

                 bc_all[i-1] = "".join(parts)+"\n"            
                 bc_all[i] = "Pt/Pinf   Tt/Tinf   Alphae    Betae   Pt/Pinf_e   Tt/Tinf_e   Pt/Pinf_nt    Tt/Tinf_nt "+"\n"
                 bc_all[i+1] = " "*6 + "".join(f"{str(value):<10}" for value in config["BoundaryConditions"][2009].values())+"\n"
     
     blocks, indices = FIND_INDEXES(config["InputOutputFiles"][0])

     with open("cfl3d.inp", "w") as f:
         f.write("I/O FILES\n")
         for filename in config["InputOutputFiles"]:
             f.write(f"{filename}\n")

         if config["KeywordDrivenInput"] is not None:
             f.write(">\n")
             for item in config["KeywordDrivenInput"]:
                 for key, value in item.items():
                     f.write(f"{key}  {value}\n")
             f.write("<\n")

         f.write(" "*5 + config["CaseTitle"]+"\n")

         f.write("     XMACH     ALPHA      BETA  REUE,MIL   TINF,DR     IALPH    IHSTRY\n")
         f.write(" "*7 + "".join(f"{str(value):<10}" for value in config["FlowConditions"].values())+"\n")

         f.write("      SREF      CREF      BREF       XMC       YMC       ZMC\n")
         f.write(" "*7 + "".join(f"{str(value):<10}" for value in config["ReferenceQuantities"].values())+"\n")

         f.write("        DT     IREST   IFLAGTS      FMAX     IUNST    CFLTAU\n")
         f.write(" "*7 + "".join(f"{str(value):<10}" for value in config["TimeStepParameters"].values())+"\n")

         f.write("     NGRID   NPLOT3D    NPRINT    NWREST      ICHK       I2D    NTSTEP       ITA\n")
         f.write(" "*7 + "".join(f"{str(value):<10}" for value in config["OptionsAndSpecifications"].values())+"\n")

         f.write("       NCG       IEM  IADVANCE    IFORCE  IVISC(I)  IVISC(J)  IVISC(K)\n")
         [f.write(" "*9 + "".join(f"{str(value):<10}" for value in config["GridForceViscousOptions"].values())+"\n") for _ in range(abs(int(config["OptionsAndSpecifications"]["NGRID"])))]

         f.write("      IDIM      JDIM      KDIM\n")
         f.writelines(blocks_splitted)

         f.write("    ILAMLO    ILAMHI    JLAMLO    JLAMHI    KLAMLO    KLAMHI\n")
         [f.write(" "*9 + "".join(f"{str(value):<10}" for value in config["LaminarRegionSpecification"].values())+"\n") for _ in range(abs(int(config["OptionsAndSpecifications"]["NGRID"])))]

         f.write("     INEWG    IGRIDC        IS        JS        KS        IE        JE        KE\n")
         [f.write(" "*9 + "".join(f"{str(value):<10}" for value in config["EmbeddedMeshSpecifications"].values())+"\n") for _ in range(abs(int(config["OptionsAndSpecifications"]["NGRID"])))]

         f.write("  IDIAG(I)  IDIAG(J)  IDIAG(K)  IFLIM(I)  IFLIM(J)  IFLIM(K)\n")
         [f.write(" "*9 + "".join(f"{str(value):<10}" for value in config["MatrixInversionAndFluxLimiter"].values())+"\n") for _ in range(abs(int(config["OptionsAndSpecifications"]["NGRID"])))]   

         f.write("   IFDS(I)   IFDS(J)   IFDS(K)  RKAP0(I)  RKAP0(J)  RKAP0(K)\n")
         [f.write(" "*9 + "".join(f"{str(value):<10}" for value in config["SpatialDifferencing"].values())+"\n") for _ in range(abs(int(config["OptionsAndSpecifications"]["NGRID"])))]

         f.writelines(bc_all)

         f.write("      MSEQ    MGFLAG    ICONSF       MTT      NGAM\n")
         f.write(" "*9 + "".join(f"{str(value):<10}" for value in config["MeshSequencingAndMultigrid"].values())+"\n")

         f.write("      ISSC EPSSSC(1) EPSSSC(2) EPSSSC(3)      ISSR EPSSSR(1) EPSSSR(2) EPSSSR(3)\n")
         f.write(" "*9 + "".join(f"{str(value):<9}" for value in config["Smoothing"].values())+"\n")

         f.write("      NCYC    MGLEVG     NEMGL     NITFO\n")
         [f.write(" "*7 + "".join(f"{str(value):<10}" for value in config["IterationsAndMultigridLevels"][i].values())+"\n") for i in range(config["MeshSequencingAndMultigrid"]["MSEQ"])]

         f.write("      MIT1      MIT2      MIT3      MIT4      MIT5\n")
         [f.write(" "*9 + "".join(f"{str(value):<10}" for value in config["CoarseGridIterations"][i].values())+"\n") for i in range(config["MeshSequencingAndMultigrid"]["MSEQ"])]

         f.writelines(one2one_blocking)

         f.write("   PATCH SURFACE DATA:\n    NINTER\n")
         f.write(" "*5 + str(config["NumberOfPatchedGridInterfaces"]["NINTER"])+"\n")

         f.write("PLOT3D OUTPUT:\n  GRID  IPTYPE  ISTART  IEND  IINC  JSTART  JEND  JINC  KSTART  KEND  KINC\n")

         if config["OptionsAndSpecifications"]["NPLOT3D"]:
             f.writelines(f"{i:6d}" + "     0" * 10 + "\n" for i in range(1, abs(int(config["OptionsAndSpecifications"]["NGRID"])) + 1))

         f.write(" MOVIE\n")
         f.write(" "*6 + str(config["MovieOption"]["IMOVIE"])+"\n")

         f.write(" PRINT OUT:\n  GRID  IPTYPE  ISTART  IEND  IINC  JSTART  JEND  JINC  KSTART  KEND  KINC\n")
         f.writelines(f"{int(blocks[j]):7d}{config["PrintOutputSpecifications"][config["OptionsAndSpecifications"]["NPRINT"]]["IPTYPE"]:7d}{''.join(f'{int(x):7d}{int(x):7d}{1:7d}' for x in indices[j])}\n" for j in range(config["OptionsAndSpecifications"]["NPRINT"]))

         f.write(" CONTROL SURFACE:\n  NCS\n   0\n  GRID  ISTART    IEND  JSTART    JEND  KSTART    KEND   IWALL   INORM\n")
         os.remove(config["Auxiliary"]["input_fn"])
     os.chdir("../")     

READ_YAML()
SPLITTER()
CFL3Dinp()
