#!/usr/bin/env python3
import os
import subprocess
import sys
import yaml
import shutil

config_file = sys.argv[1]
with open(config_file, "r") as f:
     config = yaml.safe_load(f)

shutil.copytree("0","run")
os.chdir("run")
if config["InitiliazeField"]["p-u-v-w-rho"] is not None:
    in_fi_input = ["cfl3d.inp", config["InputOutputFiles"][-1], "1"] + list(config["InitiliazeField"].values())
    subprocess.run("initialize_field", input="\n".join(in_fi_input), text=True)

os.makedirs("../data", exist_ok=True)
    
os.system(f"mpirun -np {config["Auxiliary"]["ncore_mypc"]} cfl3d_mpi < cfl3d.inp")
#os.system("cfl3d_seq < cfl3d.inp")
